Avanon gnss mag
ArduPilot/ardupilot_wiki pull request #3011
Opened 2020-09-09 01:24 UTC by avionicsanonymous

Adds pages for the Avionics Anonymous line of UAVCAN peripherals, and adds them to the positioning, rangefinder, and UAVCAN peripheral lists.

2020-09-10 18:06 UTC, Hwurzburg requested changes
the -adc page is not in any TOC, but dont worry about it...after you fix these, I will rebase, squash , and redo the UAVCAN peripherals page to a TOC format and add it there....and push to your PR, then merge....thanks

2020-09-10 18:06 UTC, Hwurzburg commented on common/source/docs/common-avanon-laserint.rst
> +The following parameter should be set on the autopilot (and then reboot the autopilot):
parameters

2020-09-10 18:06 UTC, Hwurzburg commented on common/source/docs/common-avanon-gnss-mag.rst
> +The following parameter should be set on the autopilot (and then reboot the autopilot):
parameters

2020-09-10 18:06 UTC, Hwurzburg commented on common/source/docs/common-avanon-mag.rst
> +=========================================
Mgnetometer or Compass    choose one, the other is redundant...

2020-09-10 18:06 UTC, Hwurzburg commented on common/source/docs/common-avanon-mag.rst
> +magnetometer for small unmanned vehicles. Includes a high-quality Memsic MMC5983MA magnetometer enabling
It includes...

2020-09-10 18:06 UTC, Hwurzburg commented on common/source/docs/common-avanon-mag.rst
> +sub-1-degree heading accuracy. All of this interfaces to your autopilot via robust `UAVCAN <https://uavcan.org>`__
All of these interface

2020-09-10 18:06 UTC, Hwurzburg commented on common/source/docs/common-positioning-landing-page.rst
> +    Avionics Anonymous GNSS/Mag: GNSS + Compass <common-avanon-gnss-mag>
Drop GNSS/Mag     GNSS + Compass is sufficient

2020-09-10 18:06 UTC, Hwurzburg commented on common/source/docs/common-positioning-landing-page.rst
> +    Avionics Anonymous Magnetometer: Compass <common-avanon-mag>
Same here: Compass or Magnetometer, not both

2020-09-10 18:06 UTC, Hwurzburg commented on common/source/docs/common-rangefinder-landingpage.rst
> +    Avionics Anonymous Laser Interface <common-avanon-laserint>
Name change as above please

2020-09-10 18:06 UTC, Hwurzburg commented on common/source/docs/common-uavcan-peripherals.rst
> +- `Avionics Anonymous Laser Interface <https://docs.avionicsanonymous.com/devices/laser_interface>`__
name change please as requested above

2020-09-10 23:05 UTC, avionicsanonymous commented
@Hwurzburg , thanks for the thorough review! I believe I've addressed all of your comments.

Sorry for for harassing I2C if it felt like too much "marketing" - a bit too much copy/paste from my other pages.

2020-09-10 23:07 UTC, avionicsanonymous commented
> 
> 
> the -adc page is not in any TOC, but dont worry about it...after you fix these, I will rebase, squash , and redo the UAVCAN peripherals page to a TOC format and add it there....and push to your PR, then merge....thanks

Thanks! I added the page but couldn't find any section at all for airspeed sensors, so figured I'd leave it orphaned until such a page was added.

2020-09-11 21:31 UTC, Hwurzburg commented on common/source/docs/common-avanon-adc.rst
> +temperature measurement with less than 1 degree precision. All of this interfaces to your autopilot
first change not doen

2020-09-11 21:37 UTC, Hwurzburg requested changes

2020-09-11 21:37 UTC, Hwurzburg commented on common/source/docs/common-avanon-gnss-mag.rst
> +heading accuracy. The devices interfaces to your autopilot via a robust `UAVCAN <https://uavcan.org>`__
These devices interface to ... 

or This device interfaces to...

2020-09-11 21:37 UTC, Hwurzburg commented on common/source/docs/common-avanon-mag.rst
> +better than 1-degree heading accuracy. The devices interfaces to your autopilot via a robust `UAVCAN <https://uavcan.org>`__
This device interfaces to...

2020-09-12 13:35 UTC, Hwurzburg commented
I fixed the still outstanding change I requested, added a note on the rangefinder interface that I think would otherwise cause support calls to one of us, squash, rebased, changed the UAVCAN peripherals page to allow inclusion of the Airspeed sensor in a TOC, and merged....thanks

2020-09-12 13:35 UTC, merged