added IMU temperature calibration documentation
ArduPilot/ardupilot_wiki pull request #3282
Opened 2021-01-20 23:15 UTC by tridge

the corresponding PR should be merged soon:
https://github.com/ArduPilot/ardupilot/pull/16262

2021-01-20 23:25 UTC, Hwurzburg requested changes

2021-01-20 23:25 UTC, Hwurzburg commented on common/source/docs/common-imutempcal.rst
> +.. _common-magfit:
needs to match the file name

2021-01-20 23:27 UTC, Hwurzburg commented
suggest a title Online Temperature Calibration since you have an Offline one...

2021-01-20 23:28 UTC, Hwurzburg commented
builds okay but params are unlinked since the code has not merged.....will need to add this to the Upcoming features page when we are ready to merge to get the TOC entry and it belongs there since not in a release yet....

2021-01-20 23:31 UTC, tridge commented on common/source/docs/common-imutempcal.rst
> +.. _common-magfit:
fixed

2021-01-20 23:31 UTC, tridge commented
> suggest a title Online Temperature Calibration since you have an Offline one...

the doc covers both

2021-01-20 23:32 UTC, tridge commented
> builds okay but params are unlinked since the code has not merged.....will need to add this to the Upcoming features page when we are ready to merge to get the TOC entry and it belongs there since not in a release yet....

yep, I didn't link it at all yet. We can do that when ardupilot PR merged

2021-01-20 23:37 UTC, Hwurzburg commented
> > suggest a title Online Temperature Calibration since you have an Offline one...
> 
> the doc covers both

so you can start right at the section titled Offline.... without the predecessor? may be just editorial fancy, but normally I would expect a flow like (not to suggest titles, just content partitioning): 

-common setup
-Online cal
-Offline cal
-Factory cal

we start by stating two methods.... by only one is subtitled...

2021-01-20 23:45 UTC, tridge commented
> we start by stating two methods.... but only one is subtitled...

that is because the process for doing an offline cal starts by doing an online cal. Happy to change it if you think it will work better of course

2021-01-21 02:45 UTC, tridge commented
PR is now merged, so we can add this into the TOC

2021-01-21 21:55 UTC, Hwurzburg commented
merged vai another branch

2021-01-21 21:55 UTC, closed without merging