Add cuav  gps
ArduPilot/ardupilot_wiki pull request #3309
Opened 2021-01-30 08:39 UTC by cuhome

add cuav  neo 3  and  neo 3 pro GPS

2021-02-01 04:05 UTC, Hwurzburg requested changes

2021-02-01 04:05 UTC, Hwurzburg commented on common/source/docs/common-cuav-neo-3-pro.rst
> +** Number of satellites(MAX)**
remove space before Number to get the format you want

2021-02-01 04:05 UTC, Hwurzburg commented on common/source/docs/common-cuav-neo-3.rst
> +Neo 3 is a UAV positioning module developed by  CUAV. It integrates industrial-grade compass, barometer, flight controller status light, buzzer, and safety switch all in one package. It has the chara
duplicated 3rd and 4th sentences

2021-02-01 04:05 UTC, Hwurzburg commented on common/source/docs/common-cuav-neo-3.rst
> +Neo 3 is a UAV positioning module developed by  CUAV. It integrates industrial-grade compass, barometer, flight controller status light, buzzer, and safety switch all in one package. It has the chara
the html tag is not needed at the end

2021-02-01 04:05 UTC, Hwurzburg commented on common/source/docs/common-cuav-neo-3-pro.rst
> +NEO 3 pro is UAVCAN standard GPS developed by CUAV. It integrates industrial-grade compass, barometer, flight controller status light, buzzer, and safety switch all in one package. It has the charact
the html tag is not needed at the end

2021-02-01 06:14 UTC, cuhome commented
@Hwurzburg I have modified it, please check.

2021-02-01 15:30 UTC, Hwurzburg commented on common/source/docs/common-cuav-neo-3-pro.rst
> +** Number of satellites(MAX)**
sorry...before the word "Number"

2021-02-01 15:33 UTC, Hwurzburg commented
can you change the last commit message? {git rebase -i HEAD~1.....then mark the commit for **r**eword, ctrl-x, fix the wording to something like ..."correct typos", ctrl-X }

2021-02-01 15:35 UTC, Hwurzburg commented on common/source/docs/common-cuav-neo-3-pro.rst
> +** Number of satellites(MAX)**
Sorry meant the line with the word Number

2021-02-02 01:12 UTC, cuhome commented
@Hwurzburg I used tortoisegit ui to edit it, I don't know how to do what you described, I made a new modification, please help me to check it.

2021-02-02 02:54 UTC, Hwurzburg commented
no problem...I fixed it....merging...thanks!

2021-02-02 02:55 UTC, merged