Update Cygwin package list for SITL binaries
ArduPilot/ardupilot_wiki pull request #3517
Opened 2021-05-10 18:53 UTC by TunaLobster

DELAY MERGE for ArduPilot/ardupilot#17083

The previous changes to this page went in before the PR was merged. That's on me for not saying that this was a delayed merge.

2021-05-12 21:39 UTC, TunaLobster commented
I can build locally with WSL 1, 18.04, Sphinx 4.0.1, and tweaking common_conf.py. CI seems to be failing.

2021-05-12 21:43 UTC, Hwurzburg commented
Ci fails everything....for the last few days...

2021-05-13 22:55 UTC, stephendade commented
You'll also need to update the "Set up directories/paths and extra packages in Cygwin" section to have the updatled ``ln`` commands.

2021-05-14 01:03 UTC, TunaLobster commented
Thanks Stephen! Rebased to get the CI fixes.

2021-05-27 09:53 UTC, stephendade requested changes

2021-05-27 09:53 UTC, stephendade commented on dev/source/docs/building-setup-windows-cygwin.rst
>  #. Open a web browser to `www.cygwin.com/install.html <https://www.cygwin.com/install.html>`__ and download  "setup-x86.exe"
Update to ``setup-x86_64.exe``

2021-06-01 22:11 UTC, TunaLobster commented on dev/source/docs/building-setup-windows-cygwin.rst
>  #. Open a web browser to `www.cygwin.com/install.html <https://www.cygwin.com/install.html>`__ and download  "setup-x86.exe"
Fixed!

2021-06-02 09:34 UTC, stephendade commented
Great - all good from me. LGTM

2021-06-08 23:36 UTC, merged