Give users more details to make an educated decision.
ArduPilot/ardupilot_wiki pull request #3525
Opened 2021-05-12 10:25 UTC by davidbuzz

2021-05-12 12:53 UTC, Hwurzburg requested changes

2021-05-12 12:53 UTC, Hwurzburg commented on common/source/docs/common-install-gcs.rst
> +- :ref:`Mission Planner <planner:home>` (Windows, Linux, Android): :ref:`Install Mission Planner <planner:install-mission-planner>` This is the most fully-featured and constantly updated GCS that we
```suggestion
- :ref:`Mission Planner <planner:home>` (Windows, Linux, Android): :ref:`Install Mission Planner <planner:install-mission-planner>` This GCS is the most compatible and closely tracks new features and updates in ArduPilot. It is recommended for first-time users and power users alike.  It functions best in the Windows environment.
```

2021-05-12 12:53 UTC, Hwurzburg commented on common/source/docs/common-install-gcs.rst
> +- `QGroundControl <http://qgroundcontrol.com/>`__ (Windows, Mac OS X, Linux, Android and iOS). Not bad, many people like it, seems to have less complete support for ArduPilot drones than MP (above),
```suggestion
- `QGroundControl <http://qgroundcontrol.com/>`__ (Windows, Mac OS X, Linux, Android and iOS).This is the most popular GCS for Android based systems and provides the best presentation on small format devices like cellphones. Does not have all the capabilities of Mission Planner, but has a more user-friendly interface for some functions. Operates well on all platforms
```

2021-05-12 12:53 UTC, Hwurzburg commented on common/source/docs/common-install-gcs.rst
> +- :ref:`APM Planner 2 <planner2:home>` (Windows, Mac OS X, Linux): :ref:`Install APM Planner 2 <planner2:installing-apm-planner-2>` - Originally a fork of QGC for a cross-platform GCS when MP wasn't.
```suggestion
- :ref:`APM Planner 2 <planner2:home>` (Windows, Mac OS X, Linux): :ref:`Install APM Planner 2 <planner2:installing-apm-planner-2>` -Provides basic functionality, but is not currently well maintained and updated.
```

2021-05-12 18:39 UTC, khancyr commented
A little too much engaged ! Henry suggestions are welcome !

2021-05-13 11:19 UTC, davidbuzz commented
Henry, i don't have a strong opinion about any of the wording.   I've accepted all your suggestions.

2021-05-13 12:26 UTC, Hwurzburg approved these changes
thanks...merging

2021-05-13 12:26 UTC, merged