Nitpicking
ArduPilot/ardupilot_wiki pull request #3590
Opened 2021-06-02 15:48 UTC by arBalasquide

Only proper concern is that the wiki states to set the drone to 5ft in altitude but that could be too low in some cases. Everything else is just my opinion on what reads better.

2021-06-03 03:25 UTC, rmackay9 approved these changes

2021-06-08 21:44 UTC, Hwurzburg requested changes

2021-06-08 21:44 UTC, Hwurzburg commented on copter/source/docs/ac2_followme.rst
> +-  This will bring up this window. Select the serial port that's assigned to your GPS device and the baud rate it uses.
we autobaud...so
```suggestion
-  This will bring up this window. Select the serial port that's assigned to your GPS device.
```

2021-06-08 21:49 UTC, Hwurzburg approved these changes
we need to update the images....will put it on my list...

2021-06-08 21:49 UTC, merged