EKF3 updates for opticalFlow pages
ArduPilot/ardupilot_wiki pull request #3716
Opened 2021-08-24 03:47 UTC by zhouzhiwen2000

2021-08-25 15:12 UTC, Hwurzburg requested changes
@rmackay9 you will need to verify the setup conditions....thanks

2021-08-25 15:12 UTC, Hwurzburg commented on common/source/docs/common-cheerson-cxof.rst
> +- For EKF3: (for ArduPilot 4.1 (and higher))
```suggestion
- For EKF3:  EKF3 is enabled and used by default in ArduPilot firmware 4.1 and higher
```

2021-08-25 15:12 UTC, Hwurzburg commented on common/source/docs/common-cheerson-cxof.rst
> +- Set :ref:`EK2_ENABLE <EK2_ENABLE>` = 0 to disable EKF2
remove this...not required to disable EKF2

2021-08-25 15:12 UTC, Hwurzburg commented on common/source/docs/common-openmv-optflow.rst
> +- Set :ref:`EK3_ENABLE <EK2_ENABLE>` = 1 to enable EKF2 (for ArduPilot 4.1 (and higher))
```suggestion
- Verify :ref:`EK2_ENABLE <EK2_ENABLE>` = 1 is enabling EKF2
```

2021-08-25 15:12 UTC, Hwurzburg commented on common/source/docs/common-openmv-optflow.rst
> +- Set :ref:`EK2_ENABLE <EK3_ENABLE>` = 0 to disable EKF3 (for ArduPilot 4.1 (and higher))
remove

2021-08-25 15:12 UTC, Hwurzburg commented on common/source/docs/common-openmv-optflow.rst
> +- For EKF3: (for ArduPilot 4.1 (and higher))
```suggestion
- For EKF3: EKF3 is enabled and used by default in ArduPilot firmware 4.1 and higher
```

2021-08-25 15:12 UTC, Hwurzburg commented on common/source/docs/common-cheerson-cxof.rst
> +- Set :ref:`EK3_ENABLE <EK3_ENABLE>` = 1 to enable EKF3
```suggestion
-  Verify  that ref:`EK3_ENABLE <EK3_ENABLE>` = 1 , enabling EKF3
```

2021-08-25 15:12 UTC, Hwurzburg commented on common/source/docs/common-openmv-optflow.rst
> +- Set :ref:`EK2_ENABLE <EK2_ENABLE>` = 0 to disable EKF2
remove

2021-08-25 15:12 UTC, Hwurzburg commented on common/source/docs/common-openmv-optflow.rst
> +- Set :ref:`EK3_ENABLE <EK3_ENABLE>` = 1 to enable EKF3
```suggestion
-  Verify that :ref:`EK3_ENABLE <EK3_ENABLE>` = 1, enabling EKF2
```

2021-08-25 15:12 UTC, Hwurzburg commented on common/source/docs/common-upixels-upflow.rst
> +- Set :ref:`EK2_ENABLE <EK3_ENABLE>` = 0 to disable EKF3 (for ArduPilot 4.1 (and higher))
remove

2021-08-25 15:12 UTC, Hwurzburg commented on common/source/docs/common-upixels-upflow.rst
> +- Set :ref:`EK2_ENABLE <EK2_ENABLE>` = 0 to disable EKF2
remove

2021-08-25 15:12 UTC, Hwurzburg commented on common/source/docs/common-upixels-upflow.rst
> +- Set :ref:`EK3_ENABLE <EK2_ENABLE>` = 1 to enable EKF2 (for ArduPilot 4.1 (and higher))
```suggestion
- Verify that :ref:`EK2_ENABLE <EK2_ENABLE>` = 1, enabling EKF2
```

2021-08-25 15:12 UTC, Hwurzburg commented on common/source/docs/common-upixels-upflow.rst
> +- For EKF3: (for ArduPilot 4.1 (and higher))
```suggestion
- For EKF3: EKF3 is enabled and used by default in ArduPilot firmware 4.1 and higher
```

2021-08-25 15:12 UTC, Hwurzburg commented on common/source/docs/common-upixels-upflow.rst
> +- Set :ref:`EK3_ENABLE <EK3_ENABLE>` = 1 to enable EKF3
```suggestion
-  Verify that :ref:`EK3_ENABLE <EK3_ENABLE>` = 1, enabling EKF2
```

2021-08-29 18:54 UTC, Hwurzburg approved these changes

2021-09-17 02:38 UTC, zhouzhiwen2000 commented
Is there anything else that needs refining?

2021-09-17 12:53 UTC, Hwurzburg commented
just awaiting @rmackay9 approval

2021-09-17 18:59 UTC, zhouzhiwen2000 commented
> just awaiting @rmackay9 approval

OK, i thought there was something else to modify.😂

2021-09-22 20:58 UTC, tridge approved these changes

2021-09-23 00:49 UTC, Hwurzburg commented
approved and merging

2021-09-23 00:49 UTC, merged