Add linux board (OBAL)
ArduPilot/ardupilot_wiki pull request #3759
Opened 2021-09-11 03:33 UTC by HefnySco

Adding Open Board Architecture for Linux  (Obal)  hardware board.
Obal is merged in [PR 18537](https://github.com/ArduPilot/ardupilot/pull/18537)

2021-09-11 13:10 UTC, Hwurzburg commented
this is missing the actual page

2021-09-11 13:35 UTC, HefnySco commented
> this is missing the actual page
My mistake :(

2021-09-11 15:33 UTC, Hwurzburg commented
thanks, where does one buy this board?

2021-09-11 16:13 UTC, HefnySco commented
It is open source and free.
The PCB can be fabricated for 5$ and other component can be soldered as
breakouts. This is the idea behind it.... A simple completely open source
easy to build AP board.
The link to PCB https://oshwlab.com/mohammad.hefny/Ardupilot-OBAL-FCB

My target is to provide non-profit DIY board.

On Sat, Sep 11, 2021, 17:33 Henry Wurzburg ***@***.***> wrote:

> thanks, where does one buy this board?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ArduPilot/ardupilot_wiki/pull/3759#issuecomment-917426041>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA75SNLW5J6IMRLE42MJ6KDUBNZETANCNFSM5D2P6JOA>
> .
>

2021-09-11 18:35 UTC, Hwurzburg commented
great, but unfortunately, the link to purchase the board and components does not seem to be working at the moment...for this to be more than a discuss.ardupilot.org blog post and an actual autopilot page, a way to purchase the kit  has to be available

2021-09-12 01:25 UTC, HefnySco commented
@Hwurzburg I added links to purchase the items - and you can purchase them from many other sellers-. The board gerber file is what you need to send to any PCB to make the board.

2021-09-13 12:47 UTC, brunoolivieri commented
First of all, thank you!  I am anxious to test/use that!

Did you miss the LED & Buzzer Driver (ULN2803APG) link?

Is the manual in wiki already?

2021-09-13 15:09 UTC, HefnySco commented
> Is the manual in wiki already?

@brunoolivieri 

I created this Help [https://github.com/HefnySco/OBAL](https://github.com/HefnySco/OBAL) If it is not enough please let me know.

2021-09-13 17:39 UTC, brunoolivieri commented
Thanks @HefnySco, LGTM

2021-09-16 01:10 UTC, HefnySco commented
@Hwurzburg please advise if latest updated were enough. The links contains everything user need to buy including how to get the board.

2021-09-17 01:10 UTC, Hwurzburg commented on common/source/docs/common-autopilots.rst
> +    Obal Board (Linux) <common-obal-overview>
couple of final nits....should be placed in list in alphabetical order

2021-09-17 01:11 UTC, Hwurzburg commented on common/source/docs/common-obal-overview.rst
> +=========================
these must be the same length as the text below

2021-09-17 01:11 UTC, Hwurzburg commented on common/source/docs/common-obal-overview.rst
> +=========================
these must be the same length as the text above

2021-09-17 01:11 UTC, Hwurzburg requested changes
good to go after these changes..thanks

2021-09-17 02:33 UTC, HefnySco commented
@Hwurzburg Done ... thank you for your detailed feedback.

2021-09-17 12:26 UTC, Hwurzburg commented
thanks...merging

2021-09-17 12:26 UTC, merged