add CUAV raefly and Xunwing X4
ArduPilot/ardupilot_wiki pull request #3774
Opened 2021-09-22 06:14 UTC by cuhome

2021-09-25 15:07 UTC, Hwurzburg requested changes

2021-09-25 15:07 UTC, Hwurzburg commented on common/source/docs/common-rtf.rst
> +* `CUAV - Raefly<https://store.cuav.net/shop/raefly/>`__
malformed hyperlink....need space before <https://store.cuav.net/shop/raefly/>`__

2021-09-26 01:47 UTC, cuhome commented
@Hwurzburg 
Please check it, thank you!

2021-09-26 14:03 UTC, Hwurzburg commented
tested and squashed...thanks....merging

2021-09-26 14:03 UTC, merged