Add wiki for runcam types and hardware debugging fault pin
ArduPilot/ardupilot_wiki pull request #3962
Opened 2021-12-04 17:29 UTC by andyp1per

2021-12-06 16:22 UTC, Hwurzburg commented
@andyp1per I merged the runcam stuff...thanks....then updated this PR to only be for the debug stuff in the DEV section....still needs a few questions answered....thanks

2021-12-20 13:41 UTC, Hwurzburg commented
also, Andy has said this is an alternative or maybe its a requirement?:
optional support for hard-fault debugging using soft-serial output to a pin
  To use this setup a pin like this:

    Pxx FAULT OUTPUT HIGH

  for some pin Pxx

2021-12-21 02:06 UTC, tridge approved these changes

2021-12-21 02:07 UTC, tridge requested changes

2021-12-21 02:07 UTC, tridge commented on dev/source/docs/debugging.rst
> +It is possible to output debug assertions from ChibiOS (so the debug errors that you get if you build with --enable-asserts) using a GPIO pin. To do this you need to set "HAL_GPIO_PIN_FAULT" in hwdef
you should just set FAULT pin in hwdef.dat, the HAL_GPIO_PIN_ is automatically added by the generator

2022-03-16 22:10 UTC, Hwurzburg commented
fixed build error,squashed....merging

2022-03-16 22:10 UTC, merged