SPRacingH7 install instructions
ArduPilot/ardupilot_wiki pull request #4156
Opened 2022-02-24 21:22 UTC by andyp1per

2022-02-25 00:03 UTC, nkruzan reviewed
Just some nitpicks. Thanks!

2022-02-25 00:03 UTC, nkruzan commented on common/source/docs/common-loading-firmware-onto-chibios-only-boards.rst
> +At this point you should have working firmware on the board. If you want to load new firmware you will need to follow steps 2-7 again (you cannot use Mission Planner to load firmware). If you are cer
```suggestion
At this point you should have working firmware on the board. If you want to load new firmware you will need to follow steps 2-7 again (you cannot use Mission Planner to load firmware). If you are certain that you will never want to load betaflight on the board then you can install the ArduPilot bootloader.
```

2022-02-25 00:03 UTC, nkruzan commented on common/source/docs/common-loading-firmware-onto-chibios-only-boards.rst
> +Installing the ardupilot bootloader
```suggestion
Installing the ArduPilot bootloader
```

2022-02-25 00:03 UTC, nkruzan commented on common/source/docs/common-loading-firmware-onto-chibios-only-boards.rst
> +  Caution - installing the ardupilot bootloader is a one-way operation. You cannot restore the board to factory configuration or load betaflight after this step - you would have to return the board t
```suggestion
  Caution - installing the ArduPilot bootloader is a one-way operation. You cannot restore the board to factory configuration or load betaflight after this step - you would have to return the board to Seriously Pro to be re-flashed with factory firmware
```

2022-02-25 00:03 UTC, nkruzan commented on common/source/docs/common-loading-firmware-onto-chibios-only-boards.rst
> +If you are certain that you only want to use ardupilot on the board then flashing the ardupilot bootloader enables much simpler subsequent upgrades.
```suggestion
If you are certain that you only want to use ArduPilot on the board then flashing the ardupilot bootloader enables much simpler subsequent upgrades.
```

2022-02-25 00:03 UTC, nkruzan commented on common/source/docs/common-loading-firmware-onto-chibios-only-boards.rst
> +#. You must initially have a working version of ardupilot installed on the board - follow the steps above.
```suggestion
#. You must initially have a working version of ArduPilot installed on the board - follow the steps above.
```

2022-02-25 00:03 UTC, nkruzan commented on common/source/docs/common-loading-firmware-onto-chibios-only-boards.rst
> +#. You now must remove the copy protection on the internal flash. This is a destructive operation requiring complete erasure of the flash. Ardupilot provides support to make this easy. Set:
```suggestion
#. You now must remove the copy protection on the internal flash. This is a destructive operation requiring complete erasure of the flash. ArduPilot provides support to make this easy. Set:
```

2022-02-25 00:03 UTC, nkruzan commented on common/source/docs/common-loading-firmware-onto-chibios-only-boards.rst
> +#. Download the ardupilot bootloader, e.g. https://github.com/ArduPilot/ardupilot/blob/master/Tools/bootloaders/SPRacingH7_bl.bin
```suggestion
#. Download the ArduPilot bootloader, e.g. https://github.com/ArduPilot/ardupilot/blob/master/Tools/bootloaders/SPRacingH7_bl.bin
```

2022-02-26 14:01 UTC, Hwurzburg requested changes
biggest question is "what does a Windows user do??"

2022-02-26 14:01 UTC, Hwurzburg commented on common/source/docs/common-loading-firmware-onto-chibios-only-boards.rst
> +If you are certain that you only want to use ArduPilot on the board then flashing the ardupilot bootloader enables much simpler subsequent upgrades.
```suggestion
**If you are certain that you only want to use ArduPilot on the board**, then flashing the ardupilot bootloader enables much simpler subsequent upgrades.
```

2022-02-26 16:38 UTC, andyp1per commented on common/source/docs/common-loading-firmware-onto-chibios-only-boards.rst
> +dfu-util -U AP_2MB-VERIFY.bin -s 0x90100000:0x200000
TBF these are existing issues for SPRacing users, not sure we can paper over the cracks

2022-03-01 00:13 UTC, tridge commented on common/source/docs/common-loading-firmware-onto-chibios-only-boards.rst
> +dd if=/dev/zero ibs=1k count=2048 of=AP_2MB.bin
yes, if it needs padding we should pad when we build, not require user to pad

2022-08-11 19:16 UTC, merged