Add Holybro kakuteH7mini
ArduPilot/ardupilot_wiki pull request #4220
Opened 2022-03-11 14:01 UTC by Hwurzburg

2022-03-11 20:18 UTC, andyp1per approved these changes

2022-03-12 01:37 UTC, nkruzan requested changes
some nitpicks, as always ;)

2022-03-12 01:37 UTC, nkruzan commented on common/source/docs/common-holybro-kakuteh7mini.rst
> +   -  BMP280 barometers
```suggestion
   -  BMP280 barometer
```
docs only suggest single baro

2022-03-12 01:37 UTC, nkruzan commented on common/source/docs/common-holybro-kakuteh7mini.rst
> +The KakuteF7 Mini supports OSD using :ref:`OSD_TYPE<OSD_TYPE>` 1 (MAX7456 driver).
```suggestion
The KakuteH7 Mini supports OSD using :ref:`OSD_TYPE<OSD_TYPE>` 1 (MAX7456 driver).
```

2022-03-12 01:37 UTC, nkruzan commented on common/source/docs/common-holybro-kakuteh7mini.rst
> +TThe KakuteH7 Mini supports up to 9 outputs. M1 to M4 are accessed via the connector and are :ref:`bi-directional<bidir-dshot>` capable. M5-M8 and LED are the pads shown on the above diagram. M1-M8 a
```suggestion
The KakuteH7 Mini supports up to 9 outputs. M1 to M4 are accessed via the connector and are :ref:`bi-directional<bidir-dshot>` capable. M5-M8 and LED are the pads shown on the above diagram. M1-M8 and LED outputs support DShot as well as all PWM types.
```

2022-03-12 02:13 UTC, Hwurzburg commented
thanks...fixed all

2022-03-12 02:15 UTC, nkruzan approved these changes

2022-03-14 15:54 UTC, merged