common: add sim-on-hardware information
ArduPilot/ardupilot_wiki pull request #4241
Opened 2022-03-21 22:07 UTC by peterbarker

2022-03-24 12:46 UTC, Hwurzburg requested changes
I take it this is WIP and have marked it as such...
It needs:
- better explanation of system at top, other than features...what the heck is it??
- setup and connection information
- TOC entry in the SIM section of dev

2022-03-24 12:46 UTC, Hwurzburg commented on common/source/docs/common-sim-on-hardware.rst
> +We provide a pre-compiled binary for CubeOrange at :ref:`our firmware server <https://firmware.ardupilot.org>`.
cant find it

2022-03-24 12:46 UTC, Hwurzburg commented on common/source/docs/common-sim-on-hardware.rst
> +   Simulation on Hardware is being improved all the time.  Do not be surprised if it is suggested you run the master branch to be able to take advantage of new features that have been added.
```suggestion
   Simulation on Hardware is being improved all the time.  It is suggested you run the master branch ("latest" firmware) to be able to take advantage of any new features that have been added.
```

2022-03-24 12:46 UTC, Hwurzburg commented on common/source/docs/common-sim-on-hardware.rst
> +-  parameter space is shared between the real aircraft and the simulated aircraft.  This leads to problems with sensor calibration as the sensor suite differs between the real and virtual aircraft.
```suggestion
-  parameter space is shared between the real aircraft and the simulated aircraft.  This leads to problems with sensor calibration as the sensor suite differs between the real and virtual aircraft.  Thus parameters must be wiped and rewritten to the vehicle when moving between real and simulation  firmware.
```

2022-03-24 12:46 UTC, Hwurzburg commented on common/source/docs/common-sim-on-hardware.rst
> +-  only quadcopters have been tested as working
```suggestion
-  only Quadcopters have been tested as working
```

2022-03-24 12:46 UTC, Hwurzburg commented on common/source/docs/common-sim-on-hardware.rst
> +-  actuator output is not supported without recompilation.  This is currently considered a safety feature
```suggestion
-  actuator output is not supported without recompilation of the simulation firmware as posted on the :ref:`firmware server <https://firmware.ardupilot.org>` .  This is currently considered a safety feature
```

2022-03-24 12:46 UTC, Hwurzburg commented on common/source/docs/common-sim-on-hardware.rst
> +.. _common-sim-on-hardware:
this should be a dev topic I would think...not a vehicle common topic

2022-03-27 00:41 UTC, nkruzan commented
Just some notes: 
PR for initial support in main code base is here https://github.com/ArduPilot/ardupilot/pull/19810
PR for CubeOrange-SimOnHardware is here https://github.com/ArduPilot/ardupilot/pull/20339

2022-04-05 09:24 UTC, peterbarker reviewed
>    better explanation of system at top, other than features...what the heck is it??

Added Some Words

>    setup and connection information

It really should be as simple as what's covered in here, but I'm expecting to add more notes as I receive feedback.

>    TOC entry in the SIM section of dev

I've added a note on a simulation page - but I'm pretty sure that's not what you meant here.  Can you clarify, please?

2022-04-21 00:51 UTC, peterbarker commented on common/source/docs/common-sim-on-hardware.rst
> +We provide a pre-compiled binary for CubeOrange at :ref:`our firmware server <https://firmware.ardupilot.org>`.
Fixed.

2022-04-21 00:53 UTC, peterbarker commented
@Hwurzburg what do you think this still needs before merge?

2022-04-23 19:31 UTC, Hwurzburg commented
@peterbarker   made some changes, if okay I will merge

2022-04-29 23:56 UTC, peterbarker commented on dev/source/docs/sim-on-hardware.rst
> +- communications infrastructure works in the face of real traffic
```suggestion
Simulation on Hardware allows checking that:

- mission structure is correct
- control surfaces move appropriately throughout a simulated mission
- physical failsafes (e.g. parachutes) function appropriately without putting a vehicle at risk
- communications infrastructure works in the face of real traffic
```

2022-04-29 23:56 UTC, peterbarker commented on dev/source/docs/sim-on-hardware.rst
> +The firmware is loaded on the autopilot and a GCS attached. The GPS initial location data is provided by the simulation and can be changed when compiling the firware. Setup, arming, and flying the si
```suggestion
The firmware is loaded on the autopilot and a GCS attached. The GPS initial location data is provided by the simulation and can be changed with `SIM_OPOS_LAT`, `SIM_OPOS_LNG`, `SIM_OPOS_ALT` and `SIM_OPOS_HDG` parameters. Setup, arming, and flying the simulation occurs as if sim_vehicle.py and the associated physics models for the vehicle and frame was used.
```

2022-04-29 23:56 UTC, peterbarker commented on dev/source/docs/sim-on-hardware.rst
> +.. warning:: relay outputs currently are not prevented from operation. Be careful if they are being used for payload releases or parachute deployment.
You've fixed this now.

2022-04-29 23:56 UTC, peterbarker commented on dev/source/docs/sim-on-hardware.rst
> +- Only Quadcopters have been tested as working.
```suggestion
```

Others have tested planes.  They were keen.

2022-04-29 23:56 UTC, peterbarker commented on dev/source/docs/sim-on-hardware.rst
> +      --default-param="$THISDIR/default.param" \ a typical default param file is shown `here <https://github.com/ArduPilot/ardupilot/blob/master/libraries/SITL/examples/on-hardware/default.param>`__
Perhaps move the references to the typical files to the bottom to easy copy/paste?

2022-05-04 23:06 UTC, merged