Plane: update tiltrotor FW gain note
ArduPilot/ardupilot_wiki pull request #4367
Opened 2022-05-26 21:07 UTC by IamPete1

2022-05-26 22:23 UTC, tridge approved these changes

2022-05-27 00:49 UTC, tridge requested changes

2022-05-27 00:49 UTC, tridge commented on plane/source/docs/quadplane-weathervaning.rst
> + Continuous tilt-rotor QuadPlanes will tilt motors up to :ref:`THR_MIN <THR_MIN>` times :ref:`Q_TILT_MAX<Q_TILT_MAX>` to maintain position.
TRIM_THROTTLE not THR_MIN

2022-05-27 09:52 UTC, IamPete1 commented on plane/source/docs/quadplane-weathervaning.rst
> + Continuous tilt-rotor QuadPlanes will tilt motors up to :ref:`THR_MIN <THR_MIN>` times :ref:`Q_TILT_MAX<Q_TILT_MAX>` to maintain position.
oops, Thanks.

2022-05-27 11:43 UTC, merged