Common: add Gremsy configuration for AP 4.3
ArduPilot/ardupilot_wiki pull request #4489
Opened 2022-08-08 08:50 UTC by rmackay9

AP 4.3.x includes a new Gremsy specific gimbal driver.  This update adds a new section at the bottom of the existing page to clarify the setup for use with AP 4.3.

This PR also includes a couple of "drive by" changes to clarify that the existing (e.g. 4.2 and earlier) setup instructions work for many Gremsy gimbals (not just the Pixy-U) and also clarify that the autopilot must be rebooted after MNT_TYPE is set.

2022-08-08 23:18 UTC, Hwurzburg requested changes

2022-08-08 23:18 UTC, Hwurzburg commented on common/source/docs/common-gremsy-pixyu-gimbal.rst
> +---------------------
title underline too short

2022-08-08 23:45 UTC, rmackay9 commented on common/source/docs/common-gremsy-pixyu-gimbal.rst
> +---------------------
fixed, thanks!

2022-08-09 00:14 UTC, merged

2022-08-09 00:53 UTC, rmackay9 commented
Thank you very much!