Add AP_Periph DShot and PWM example
ArduPilot/ardupilot_wiki pull request #4524
Opened 2022-08-22 19:07 UTC by TunaLobster

Adds a page to hold examples of using AP_Periph for different use cases. First one up with the DShot and PWM example.

2022-08-22 20:20 UTC, Hwurzburg requested changes
I think its good to have pages for specific nodes and their setup, like the autopilot pages....but this appears as if generic, when its not....it does not show how to create a specific node example like the MatekL431-Schot...its specific to the MatekL431-DShot, specifically..which is not in stable, by the way, but master....and should be an upcoming feature for 4.3.......

We could have a landing page for the existing AP_Periph implementations with setup instructions like this for specific firmware/boards linked from it....L431-DShot could be the first link from that page...but it needs to be like the autopilot hardware pages...

Alternatively or in addition to, we could have a tutorial on how to create a specific example, like the MatekL431_Dshot or MatekL431-Airspeed, etc.

so, this needs some work to fit into the hardware board page category....

just another cursory comment,  I am not a big fan of the contents link at the top having sub-bullets....perhaps this can be eliminated whenever its used...maybe just use plain links to tags below?

assuming this evolves into a landing page, with specific node pages linked like the MatekL431-Airspeed or Dshot, then a normal TOC would be the links to those

2022-08-23 12:55 UTC, Hwurzburg commented
Thinking more about this...we already have a page that points to specific implementations....https://ardupilot.org/plane/docs/common-uavcan-peripherals.html

we need to add a MatekL431-DShot page (as well as more or the new ones)....so if we take the content of the blog post and turn it into a page similar to https://ardupilot.org/plane/docs/common-matek-uavcan-dlvr.html base on what you already started...I think that would be the best approach...

we still could use a dev page on exactly how to create a new DroneCAN AP_Periph (since they all are DroneCAN periphs)

2022-08-23 19:39 UTC, TunaLobster commented
The generic presentation was purposeful. Having to create a new page for each of the roles for each generic node (ARK CAN node, mRo node, and Matekl431 just to name a few) can play is a lot of pages and would require a new page for each board when a new feature that works on all of them is added. The setup of the parameters for the roles is mostly agnostic to board just as ArduPlane parameters work between a Cube Orange and an Omnibus F4. The restriction would come when AP_Periph features grow to be too large to fit on the smaller nodes.

Each feature can have its own section on this page and this page linked to from each node board. I just picked the dev docs for the page because the parameters for nodes are also hosted there (even though I did not include :ref: directives to each parameter). I could add the AP_Periph parameters as a common page and have this page become a common page too. Then it could be linked to from the DroneCAN Peripherals landing page. I also placed it here because it is a advanced user use case to be setting up PWM/DShot nodes on an aircraft. It is also only a use case for larger aircraft where PWM signals can get wonky due to distance and radio noise.

The contents directive was used to have a page contents table that is automatically generated when new headings are added to the page. To me that would make reviewing and editing a little easier. Also having all of the capabilities described in one place is nice. I think one other use case for this directive would be the RC Options page. Right now a lot of the options are not documented beyond just a name. It generates many questions and is a common reply that an RC option does what a user wants. Having a contents at the top of the page for that page would also be useful IMO.

2022-08-23 20:56 UTC, Hwurzburg commented
"I think one other use case for this directive would be the RC Options page. Right now a lot of the options are not documented beyond just a name."
if any are not documented, please point them out...there is a detailed explanation of each one following the table...

2022-08-23 21:13 UTC, TunaLobster commented
> "I think one other use case for this directive would be the RC Options page. Right now a lot of the options are not documented beyond just a name." if any are not documented, please point them out...there is a detailed explanation of each one following the table...

Sorry. That was the servo functions table. I was trying to work out where I was going to add the scaled RC pass through details. I'll be looking at https://ardupilot.org/plane/docs/servo-functions.html and https://ardupilot.org/copter/docs/common-rcoutput-mapping.html and https://ardupilot.org/copter/docs/common-servo.html for that update. Which does have things missing and scattered and not using [xsite wiki] tags and not referenced to each other. Future PR though.

The contents tag along with a [sectnum](https://docutils.sourceforge.io/docs/ref/rst/directives.html#automatic-section-numbering) directive might make the long table pages more navigable. Right now using crtl+f is the best option to find the needed information and that's just not a great UX design to rely on a a lot of scrolling or a browser feature to use the documentation.

2022-08-23 21:28 UTC, Hwurzburg commented
the common-rcoutput-mapping should be the central spot for ALL servo/motor functions......for all vehicles.....like your scaled pass through that will be in Future wiki changes until we beta 4.3...its probably missing a few like scripting outputs, and the RCMAP replacements.....any help in updating those would be appreciated...

...the individual vehicle pages in setup, should have the primary vehicle functions like planes servo/motor functions...of which their are many....copter is mostly motors and is covered in its motors setup page...rover has a motor and servo page for its vehicle setup...but the rcoutput-mapping page should have every output type listed...

....common-servo is a peripherals page and very old

2022-08-24 12:49 UTC, Hwurzburg commented
@TunaLobster just a follow up....I went thru the rcoutput mapping page, and every output except for the 2 WingSail and  2 Alarm outputs are documented...and those are waiting for wiki inputs from the authors....so 4 pins out of 139...

2022-08-29 19:59 UTC, Hwurzburg commented
@TunaLobster fyi, In May I had added the Matek L431 Dshot reference and link to Tridge's discuss post on his page https://ardupilot.org/plane/docs/common-uavcan-adapter-node.html..... but I think a tutorial on how someone actually goes about creating a specific AP_Perph device and hwdef would be really a good addition to the dev wiki...

2022-08-29 22:47 UTC, TunaLobster commented
I'll move this info to a common page then. It is still generic to each of the nodes that have outputs set up on headers like the Matek L431. Might be worth while to split the list of supported DroneCAN devices into generic and purpose built sensor categories.

2022-08-29 22:49 UTC, Hwurzburg commented
There are already split

2022-09-02 17:30 UTC, Hwurzburg commented
expanded, made nomenclature more consistent....will merge if your okay with it....

2022-09-02 17:43 UTC, TunaLobster commented
LGTM! Fixed a few punctuation things.

2022-09-02 19:03 UTC, merged