Update common-here-plus-gps.rst
ArduPilot/ardupilot_wiki pull request #4598
Opened 2022-09-12 10:56 UTC by mnumanuyar

I had a chance to use ublox rtk and do some tests. During those test I observed inconsistent surveyin duration. I have asked this situation in some forums, but didnt get any answer.

I can share any data to prove this claim or try to do my tests again

below are some post where I asked relevant questions

https://discuss.ardupilot.org/t/here-rtk-surveyin-duration/90264
https://discuss.px4.io/t/rtk-surveyin-duration/28894
https://discuss.cubepilot.org/t/here-3-rtk-surveyin-duration-inconsistency/9516/2

ps: my changes only adds a note, I am not sure why it shows paragraph before as changed

2022-09-12 12:54 UTC, Hwurzburg requested changes

2022-09-12 12:54 UTC, Hwurzburg commented on common/source/docs/common-here-plus-gps.rst
> +   These duration could vary greatly by various factors. For example, to achieve the absolute accuracy of 2m could take an hour.
```suggestion
   Duration required to obtain a given survey-in accuracy could vary greatly depending on various factors such as: sky-view obstructions, local rf interference, number of constellations visible at the location, firrmware version of GPS, etc.
```

2022-09-12 15:28 UTC, mnumanuyar commented
Thank you for fast response. I think an upper limit for expectations would be very usefull for people who are considering rtk.  I am aware 1 hour seems unreasonable but as i said , i could share any test data requested.

2022-09-12 15:33 UTC, mnumanuyar commented
Also I am not familiar with ci/cd but [this](https://github.com/ArduPilot/ardupilot_wiki/blob/4a5ee5ff4ff3bae974a7eab2d50ce568f5761e43/common_conf.py#L5) seem to be problem according to [here](https://stackoverflow.com/questions/48459409/why-does-sphinx-conf-py-gives-me-an-error-for-trying-to-import-sys). I am not sure how to test it tough

2022-09-12 17:59 UTC, Hwurzburg commented
> Also I am not familiar with ci/cd but [this](https://github.com/ArduPilot/ardupilot_wiki/blob/4a5ee5ff4ff3bae974a7eab2d50ce568f5761e43/common_conf.py#L5) seem to be problem according to [here](https://stackoverflow.com/questions/48459409/why-does-sphinx-conf-py-gives-me-an-error-for-trying-to-import-sys). I am not sure how to test it tough

no, CI was failing since the copter site was down...restarted the jobs

2022-09-12 18:03 UTC, Hwurzburg commented
> Thank you for fast response. I think an upper limit for expectations would be very usefull for people who are considering rtk. I am aware 1 hour seems unreasonable but as i said , i could share any test data requested.

one hour for 2M/60sec indicates something is wrong....one of those factors is in play...what gps are you using? does it have a clear sky view in all directions and angles?and NOT indoors....what is your location? are you using mission planner or trying to get a survey-in started with UBLOX U-Center

2022-09-14 04:51 UTC, mnumanuyar commented
I am using here +rtk for base (and here 3 as gps but since my problem is with surveyin time, this does not factor in) initally i tried to implement a custom version of px4 gps module, but then I also replicated the issue with mission planner and qground. I am testing on the roof of my workplace,
The interesting thing is, my surveyin times changes day-to-day. What I mean is surveyin duration changes even tough I replicaed my tests. 10 min survey-in could become hour long next day

2022-09-15 12:09 UTC, merged