Add html link to MAV_CMD_NAV_WAYPOINT
ArduPilot/ardupilot_wiki pull request #4726
Opened 2022-11-16 08:29 UTC by Geoffroy-Milton-Innovation

2022-11-19 17:22 UTC, Hwurzburg requested changes

2022-11-19 17:22 UTC, Hwurzburg commented on dev/source/docs/code-overview-adding-a-new-mavlink-message.rst
> +MAV_CMD_NAV_TRICK similar to the `MAV_CMD_NAV_WAYPOINT <https://mavlink.io/en/messages/common.html#MAV_CMD_NAV_WAYPOINT>` definition
as written link is not active:
```suggestion
MAV_CMD_NAV_TRICK similar to the `MAV_CMD_NAV_WAYPOINT <https://mavlink.io/en/messages/common.html#MAV_CMD_NAV_WAYPOINT>`__  definition
```

2022-11-27 14:11 UTC, Hwurzburg commented
@Geoffroy-Milton-Innovation  please squash and I will merge...thanks

2022-11-28 13:36 UTC, Geoffroy-Milton-Innovation commented
I didnt know how to squash and when i tried it didnt works, so I ended up deleting the repo XD

2022-11-29 15:27 UTC, Hwurzburg commented
squashed and merged on another PR...thanks

2022-11-29 15:27 UTC, closed without merging