Dual Helicopter setup wiki
ArduPilot/ardupilot_wiki pull request #4755
Opened 2022-11-29 04:30 UTC by bnsgeyer

This PR adds a basic setup wiki for dual helicopters.

2022-11-29 13:34 UTC, Hwurzburg requested changes
Just build error review....will read for content later....moving a bit slow with COVID right now

2022-11-29 13:34 UTC, Hwurzburg commented on copter/source/index.rst
> +   Dual Helicopters <docs/dual_helicopter>
build error
```suggestion
   Dual Helicopters <docs/dual-helicopter>
```

2022-11-29 13:34 UTC, Hwurzburg commented on copter/source/docs/dual-helicopter.rst
> +.. _dual_helicopter:
build error
```suggestion
.. _dual-helicopter:
```

2022-11-29 13:34 UTC, Hwurzburg commented on copter/source/docs/dual-helicopter.rst
> +- :ref:`H_COL_MAX<H_COL_MAX__AP_MotorsHeli_Dual>`- PWM for maximum collective pitch on forward rotor head that corresponds to :ref:`H_COL_ANG_MAX<H_COL_ANG_MAX>`
not defined in Dual...
```suggestion
- :ref:`H_COL_MAX<H_COL_MAX_>`- PWM for maximum collective pitch on forward rotor head that corresponds to :ref:`H_COL_ANG_MAX<H_COL_ANG_MAX>`
```

2022-11-29 13:34 UTC, Hwurzburg commented on copter/source/docs/dual-helicopter.rst
> +- :ref:`H_COL_MAX<H_COL_MAX__AP_MotorsHeli_Dual>`- PWM for maximum collective pitch on forward rotor head that corresponds to :ref:`H_COL_ANG_MAX<H_COL_ANG_MAX>`
similarly below also

2022-11-29 13:34 UTC, Hwurzburg commented on copter/source/docs/dual-helicopter.rst
> +- :ref:`H_COL_MIN<H_COL_MIN__AP_MotorsHeli_Dual>` - PWM for minimum collective pitch on forward rotor head that corresponds to :ref:`H_COL_ANG_MIN<H_COL_ANG_MIN>`
not defined in Dual
```suggestion
- :ref:`H_COL_MIN<H_COL_MIN>` - PWM for minimum collective pitch on forward rotor head that corresponds to :ref:`H_COL_ANG_MIN<H_COL_ANG_MIN>`
```
similarly below also

2022-11-29 14:48 UTC, bnsgeyer commented on copter/source/docs/dual-helicopter.rst
> +.. _dual_helicopter:
fixed. Thanks!

2022-11-29 14:48 UTC, bnsgeyer commented on copter/source/docs/dual-helicopter.rst
> +- :ref:`H_COL_MAX<H_COL_MAX__AP_MotorsHeli_Dual>`- PWM for maximum collective pitch on forward rotor head that corresponds to :ref:`H_COL_ANG_MAX<H_COL_ANG_MAX>`
fixed. Thanks!

2022-12-05 14:08 UTC, Hwurzburg commented
should we point the reader to some setup sections in single blade to help then set collective ranges, etc. for the parameter values? if only to give them some clue

2022-12-09 13:23 UTC, Hwurzburg commented
sorry, COVID delay....added a few notes....merging

2022-12-09 13:23 UTC, merged

2022-12-09 16:00 UTC, bnsgeyer commented
@Hwurzburg no problem.  I appreciate the help. I will look at this again when I get time to see if I can make additional improvements so it provides a better flow. I’m glad we were able to get this in. There really isn’t anything out there that helps users with dual heli’s.