Common: add main-loop-slow instructions to when-problems-arise
ArduPilot/ardupilot_wiki pull request #4761
Opened 2022-11-30 06:32 UTC by rmackay9

This adds advice to the "When Problems Arise" page on how users may deal with slow Main Loop rates.

All advice welcome on changes or additional steps users should take.

This is related to

- https://github.com/ArduPilot/ardupilot/issues/22316
- https://github.com/ArduPilot/ardupilot/pull/22320

2022-11-30 06:39 UTC, peterbarker requested changes

2022-11-30 06:39 UTC, peterbarker commented on common/source/docs/common-when-problems-arise.rst
> +Some autopilots with slower CPUs (e.g. STM32F4) may not be fast enough to run all enabled features while also keeping the main loop running at the optimal rate (400hz for multicopters and helicopters
```suggestion
Some autopilots with slower CPUs (e.g. STM32F4) may not be fast enough to run all enabled features while also keeping the main loop running at the optimal rate (400hz for multicopters and helicopters, 300hz for quadplanes, 50hz for planes, rovers and boats).  The ArduPilot scheduler is forced to make compromises and may slow down the main loop resulting in messages like, "Main Loop slow (320hz <400hz)".  In these situations disabling some features as listed below may help.
```

2022-11-30 08:08 UTC, tridge requested changes

2022-11-30 08:08 UTC, tridge commented on common/source/docs/common-when-problems-arise.rst
> +- Reduce the main loop rate by lowering :ref:`SCHED_LOOP_RATE <SCHED_LOOP_RATE>` (for multicopters try as low as 200)
i think the only valid one here is SCHED_LOOP_RATE

2022-11-30 14:57 UTC, khancyr commented on common/source/docs/common-when-problems-arise.rst
> +
Disabling LUA
Disabling STRL
Disabling CAN 
if they aren't used.

Could be usefull to point to the custom build server too as we can hard remove those heasily !

2023-05-08 20:08 UTC, Hwurzburg commented
@rmackay9 reminder....ball in your court on this

2024-02-02 01:01 UTC, closed without merging

2024-02-02 01:01 UTC, rmackay9 commented
Since this we've extended the [pre-arm checks page](https://ardupilot.org/copter/docs/common-prearm-safety-checks.html) to include brief instructions on this particular issue so I'll close this PR.

2024-06-13 11:00 UTC, guarav00tanwar commented
I have setup multi-drone-simulation in Gazebo with SITL. I have PC with intel xeon , 32Gb ram. So hardware was not an issue.  So, what i did is, I changed some parameters in SITL as follow;  **LOG_BITMASK - 156126.0  (old value- 176126.0)** **LOG_FILE_BUFSIZE - 100  (old value- 200)** **SCHED_LOOP_RATE - 200  (old value- 400)**  this worked for me