add makeflyeasy PixPilot-V6
ArduPilot/ardupilot_wiki pull request #4840
Opened 2022-12-28 09:25 UTC by Cedric0489

2022-12-28 13:09 UTC, Hwurzburg commented
@Cedric0489 need to add to common-autopilots.rst   also, if the power module is NOT included, we will need to add some words around the battery mon params that they would need adjustment for other power modules....finally, we should note which UARTs have DMA

2023-01-03 07:24 UTC, Cedric0489 commented
> @Cedric0489 need to add to common-autopilots.rst also, if the power module is NOT included, we will need to add some words around the battery mon params that they would need adjustment for other power modules....finally, we should note which UARTs have DMA
power module is included in this flight control. I have added PixPilot-v6 to the common-autopilots.rst and noted uarts dma-enabled.

2023-01-04 17:30 UTC, Hwurzburg requested changes
a few build errors have come in

2023-01-04 17:30 UTC, Hwurzburg commented on common/source/docs/common-makeflyeasy-PixPilot-V6.rst
> +=========================
remove indent before "Connector"

2023-01-04 17:30 UTC, Hwurzburg commented on common/source/docs/common-makeflyeasy-PixPilot-V6.rst
> +---------------
underline too short

2023-01-04 17:30 UTC, Hwurzburg commented on common/source/docs/common-makeflyeasy-PixPilot-V6.rst
> +Power1, Power2 ports
need a space about this line

2023-01-05 13:32 UTC, Hwurzburg commented
thanks..merging

2023-01-05 13:32 UTC, merged