Update common-servo.rst for digital servos
ArduPilot/ardupilot_wiki pull request #4887
Opened 2023-01-19 17:25 UTC by timtuxworth

Digital servos support higher update rates using the SERVO_RATE parameter, but this is only a good idea if all the servos on a vehicle are digital

2023-01-19 19:38 UTC, Hwurzburg requested changes
a few clarifying nit picks

2023-01-19 19:38 UTC, Hwurzburg commented on common/source/docs/common-servo.rst
> +-  If using Plane or Rover where all pins update at ``SERVO_RATE`` which defaults to 50hz, any unused
```suggestion
-  If using Plane or Rover where all PWMN outputs update at :ref:`SERVO_RATE<SERVO_RATE>`, which defaults to 50hz, any unused
```

2023-01-19 20:37 UTC, timtuxworth commented
@Hwurzburg - unfortunately my change from "PixHawk" to "AutoPilot" - makes some of the details in this section about setting up a standard autopilot incorrect I think. I thought it made sense to change it because many people these days are using a variety of other controllers, but the comments about limitations/defaults on the relay pinouts are not correct as they are specific to the PixHawk (and probably only the PixHawk 1). Should I change this too, or leave it for a separate PR?

2023-01-19 21:23 UTC, Hwurzburg commented
nah, we talk about MAIN and AUX a lot of places and that applies to most of the high end autopilots that use an IOMCU, so its fine...I will squash this and merge tomorrow when I have time....thanks

2023-01-22 20:15 UTC, Hwurzburg commented
squashed and merging...thanks

2023-01-22 20:15 UTC, merged