update.py: Reprint update.py error messages at the end
ArduPilot/ardupilot_wiki pull request #4911
Opened 2023-01-30 00:03 UTC by TunaLobster

2023-01-30 14:09 UTC, Hwurzburg commented
something is wrong with this....I tested locally by creating an error in the airspeed sensor page and building plane and do get the report:
Reprinting error messages:
[update.py][error]: Remove character before ref directive in "common/source/docs/common-airspeed-sensor.rst" on line number 9
[update.py][error]: 1 errors during Wiki build

but then fixing it and re-running a build for plane I get this:
Build finished. The HTML pages are in build/html.
Reprinting error messages:
[update.py][error]: Remove character before ref directive in "rover/source/docs/common-airspeed-sensor.rst" on line number 9
[update.py][error]: Remove character before ref directive in "copter/source/docs/common-airspeed-sensor.rst" on line number 9
[update.py][error]: 2 errors during Wiki build

so something is broken
also, if you can print the report on the std error output, it will appear in my daily cron job that I check the build daily for build errors (although I don't look EVERY day at it...maybe every other day)

2023-01-31 16:03 UTC, Hwurzburg requested changes
looks good....one small change to make it perfect

2023-01-31 16:03 UTC, Hwurzburg commented on update.py
> +            print(f"[update.py][error]: {msg}", file=sys.stderr)
```suggestion
            print(f"\033[1;31m[update.py][error]: {msg}", file=sys.stderr)
```

2023-01-31 17:22 UTC, TunaLobster commented
IIRC, color might be hit or miss in some terminals. Added the color reset tag to the end of the string.

2023-01-31 18:30 UTC, Hwurzburg commented
thanks

2023-01-31 18:30 UTC, merged