Common: add viewpro to upcoming features
ArduPilot/ardupilot_wiki pull request #4936
Opened 2023-02-10 05:17 UTC by rmackay9

This adds a wiki page for the ViewPro gimbal support which will be included in 4.4.  The corresponding flight code PR is https://github.com/ArduPilot/ardupilot/pull/22892

I have tested this on my local machine and it looks fine and no errors.

2023-02-10 16:52 UTC, Hwurzburg requested changes

2023-02-10 16:52 UTC, Hwurzburg commented on common/source/docs/common-viewpro-gimbal.rst
> +  - VIEP_CAM_SWLOW, VIEP_CAM_SWMID, and VIEP_CAM_SWHIGH control the active camera when the aux switch is the low, medium and high position respectively.  Possible values are
```suggestion
  - When the driver script is run, it creates three new parameters : VIEP_CAM_SWLOW, VIEP_CAM_SWMID, and VIEP_CAM_SWHIGH. These control the active camera when the aux switch is the low, medium and high position respectively.  Possible values are
```

2023-02-10 16:52 UTC, Hwurzburg commented on common/source/docs/common-viewpro-gimbal.rst
> +- Set VIEP_ZOOM_SPEED to control speed of zoom (value between 0 and 7)
```suggestion
- Set VIEP_ZOOM_SPEED parameter created by the driver script to control the speed of zoom (value between 0 and 7)
```

2023-02-16 07:50 UTC, rmackay9 commented
The flight code PR has gone in now so maybe we can merge this?

2023-02-16 12:38 UTC, Hwurzburg commented
done..thanks

2023-02-16 12:38 UTC, merged