Note for dynamic harmonics and narrower bandwidth
ArduPilot/ardupilot_wiki pull request #4948
Opened 2023-02-19 05:22 UTC by MichelleRos

Add a note about dynamic notches and latency. 

@tridge @andyp1per let me know if this makes sense. 
Does it nead a suggested notch width?

2023-02-19 07:28 UTC, andyp1per commented
Yes I recommend starting with f/4 in this instance

2023-02-19 07:28 UTC, andyp1per approved these changes

2023-02-19 13:47 UTC, Hwurzburg requested changes
per Andy's comment

2023-02-19 13:47 UTC, Hwurzburg commented on common/source/docs/common-esc-telem-based-notch.rst
> +   If you set the dynamic harmonics option (i.e. a notch per motor) mentioned below, the bandwidth should not be half the frequency. It should be greatly reduced as more notches cause more phase lag
```suggestion
   If you set the dynamic harmonics option (i.e. a notch per motor) mentioned below, the bandwidth should not be half the frequency. It should be greatly reduced as more notches cause more phase lag (i.e. latency), thus the bandwidth needs to be reduced to maintain a reasonable phase lag, else oscillation and a poorer tune will result despite the more accurate filtering compared to throttle-based filtering. For example, with four motors, :ref:`INS_HNTCH_FREQ<INS_HNTCH_FREQ>` / 4 is suggested as a starting point.
```

2023-02-21 17:10 UTC, MichelleRos commented
I've updated it.

2023-02-21 21:17 UTC, Hwurzburg commented
thanks...

2023-02-21 21:17 UTC, merged