Update Installation Instructions for Linux
ArduPilot/ardupilot_wiki pull request #5004
Opened 2023-03-09 07:26 UTC by billbonney

2023-03-09 14:12 UTC, Hwurzburg commented
I dont think this is correct....all APMPlanner releases should be via the firmware server, I think....  if they are not there, then there is a problem...@peterbarker please confirm....thanks

2023-03-11 22:59 UTC, billbonney commented
> I dont think this is correct....all APMPlanner releases should be via the firmware server, I think.... if they are not there, then there is a problem...@peterbarker please confirm....thanks

Why would that be a problem? You requested the links be updated. And this matches that request.

see https://github.com/ArduPilot/apm_planner/issues/1280

2023-03-11 23:10 UTC, peterbarker requested changes
@Hwurzburg releasing straight-from-github is a legitimate project thing now-adays.

I reckon it's a change, so I've marked it DevCallTopic to make sure everyone's aware - but I'm pretty sure everyone will be, "Someone's doing fresh releases?!  Great stuff!" and we'll want to merge this :-)

2023-03-11 23:10 UTC, peterbarker commented on planner2/source/docs/installation-for-linux.rst
> +Download the latest deb file for your machine from GitHub.
This doesn't look right - looks like it's all AppImage now.

2023-03-12 10:56 UTC, peterbarker commented
@billbonney I've dismissed my stale review.  I wonder if the mention of OpenSuse repo could also go away - I guess it's probably very stale.  Not trying to stretch this PR, just observing.

2023-03-12 16:51 UTC, billbonney commented
> @billbonney I've dismissed my stale review. I wonder if the mention of OpenSuse repo could also go away - I guess it's probably very stale. Not trying to stretch this PR, just observing.

Yep, we can remove that. Since AppImages are the 'run anywhere' solution

2023-05-08 20:07 UTC, merged