add FFT post filter info
ArduPilot/ardupilot_wiki pull request #5034
Opened 2023-03-21 20:18 UTC by Hwurzburg

2023-03-22 10:28 UTC, andyp1per requested changes

2023-03-22 12:14 UTC, Hwurzburg commented on common/source/docs/common-imu-fft.rst
> +The best use of the FFT notch filter is in addition to other dynamic harmonic notch filter (Throttle, ESC, or RPM based), using the post filter chain :ref:`FFT_OPTIONS<FFT_OPTIONS>` bit.
why not the other two??

2023-03-22 12:14 UTC, Hwurzburg commented on common/source/docs/common-imu-fft.rst
> +Normally, the FFT analysis for adjusting the center frequency is done by measuring the noise directly at the input to the FFT notch filter. However, if bit 0 of :ref:`FFT_OPTIONS<FFT_OPTIONS>` is set
done

2023-03-22 13:09 UTC, andyp1per commented on common/source/docs/common-imu-fft.rst
> +The best use of the FFT notch filter is in addition to other dynamic harmonic notch filter (Throttle, ESC, or RPM based), using the post filter chain :ref:`FFT_OPTIONS<FFT_OPTIONS>` bit.
don't understand your question - other two what?

2023-03-22 13:48 UTC, andyp1per commented on common/source/docs/common-imu-fft.rst
> +The best use of the FFT notch filter is in addition to other dynamic harmonic notch filter (Throttle, ESC, or RPM based), using the post filter chain :ref:`FFT_OPTIONS<FFT_OPTIONS>` bit.
The FFT filter can be used without post-filter - your text implies that you should always use it post filter. Maybe something like: "The best post-filter use of the FFT notch filter.."

2023-03-22 14:48 UTC, andyp1per commented on common/source/docs/common-imu-fft.rst
> +The best use of the FFT notch filter is in addition to other dynamic harmonic notch filter (Throttle, ESC, or RPM based), using the post filter chain :ref:`FFT_OPTIONS<FFT_OPTIONS>` bit.
Still not agreeing with the text implication that the best use for FFT notch is post-filter. FFT notch is a tool that can be used effectively when the circumstances allow/dictate - just like ESC or Throttle based notch

2023-03-22 20:11 UTC, andyp1per commented on common/source/docs/common-imu-fft.rst
> +The best use of the FFT notch filter is in addition to other dynamic harmonic notch filter (Throttle, ESC, or RPM based), using the post filter chain :ref:`FFT_OPTIONS<FFT_OPTIONS>` bit.
"The using the FFT notch filter post-filter works best in conjunction with another notch filter driven by an alternative mechanism such as throttle, ESC, or RPM using the post filter chain :ref:`FFT_OPTIONS<FFT_OPTIONS>` bit."

2023-03-26 14:18 UTC, andyp1per commented on common/source/docs/common-imu-fft.rst
> +The best use of the FFT notch filter is in addition to other dynamic harmonic notch filter (Throttle, ESC, or RPM based), using the post filter chain :ref:`FFT_OPTIONS<FFT_OPTIONS>` bit.
I don't think its possible to say what the optimum configuration is - it really depends on the vehicle.

In terms of the wording I think the word "filter" is messing with you. We could use the term "post-LPF" to determine position and then "notch filter" might make more sense

2023-03-26 16:48 UTC, Hwurzburg commented on common/source/docs/common-imu-fft.rst
> +The best use of the FFT notch filter is in addition to other dynamic harmonic notch filter (Throttle, ESC, or RPM based), using the post filter chain :ref:`FFT_OPTIONS<FFT_OPTIONS>` bit.
okay another try at it

2023-04-22 12:28 UTC, merged