Rover menu reorganization and slight content improvement
ArduPilot/ardupilot_wiki pull request #5282
Opened 2023-07-16 01:54 UTC by brianmusslewhite

2023-07-16 14:30 UTC, Hwurzburg requested changes
thanks...a few requested changes...please squash to a commit once done, or I can before merging...

2023-07-16 14:30 UTC, Hwurzburg commented on rover/source/index.rst
>      Autopilot Hardware Options <docs/common-autopilots>
this is one of the merge conflicts
```suggestion
    Choosing an AutoPilot <docs/common-autopilots>
```

2023-07-16 14:30 UTC, Hwurzburg commented on common/source/docs/common-GCS.rst
> +[copywiki destination="copter,rover"]
```suggestion
[copywiki destination="copter,plane,rover"]
```
another merge conflict

2023-07-16 14:30 UTC, Hwurzburg commented on rover/source/docs/rover-introduction.rst
> +    Ready to Fly Vehicles <common-rtf>
special title since its Rover
```suggestion
    Ready to Drive Vehicles <common-rtf>
```

2023-07-16 14:30 UTC, Hwurzburg commented on rover/source/docs/rover-video-demonstrations.rst
> +   Please add, or let a dev know, of any additional videos or use cases that are relevant to include here!
```suggestion
   Please add, or let a dev know, of any additional videos or use cases that are relevant to be included here!
```

2023-07-16 14:30 UTC, Hwurzburg commented on rover/source/docs/introduction.rst
> +Options are available to either select from a list of ready-to-drive vehicles or to assemble your own.
```suggestion
Can either select from a list of :ref:`ready-to-drive vehicles<common--rtf>` or  assemble your own (See below).
```

2023-07-16 14:30 UTC, Hwurzburg commented on rover/source/index.rst
> +This firmware supports not only conventional configurations, but also extends to balance bots, walking robots, and sailboats.
```suggestion
This firmware supports not only conventional 3 or 4 wheel configurations, but also extends to boats, sailboats, balance bots, and walking robots.
```

2023-07-16 18:06 UTC, brianmusslewhite commented
I committed all of the updates but it was getting a little messy to squash. Can you squash when you merge?

2023-07-16 19:05 UTC, Hwurzburg commented
LGTM...merging...thanks

2023-07-16 19:05 UTC, merged

2023-07-16 23:23 UTC, rmackay9 commented
@brianmusslewhite,

Thanks for the help on the wiki!

2023-07-17 00:58 UTC, brianmusslewhite commented
> @brianmusslewhite,
> 
> Thanks for the help on the wiki!

You're welcome!