updated autopilot menu order and page intro
ArduPilot/ardupilot_wiki pull request #5300
Opened 2023-07-22 20:06 UTC by brianmusslewhite

I updated the menu level so that when "Choosing an Autopilot" is clicked, it does not require another click to see the categories. I also reorganized the intro of the page accordingly.

2023-07-26 18:37 UTC, Hwurzburg requested changes

2023-07-26 18:37 UTC, Hwurzburg commented on common/source/docs/common-autopilots.rst
> +ArduPilot runs on many different autopilot boards. Selecting the right board depends on the physical restraints of the
```suggestion
ArduPilot runs on many different autopilot boards. Selecting the right board depends on the physical constraints of the
```

2023-08-01 00:27 UTC, brianmusslewhite commented
@Hwurzburg This should be ready to merge. Good catch! I overlooked that

2023-08-01 00:30 UTC, Hwurzburg approved these changes

2023-08-01 00:30 UTC, merged