add ros2-cartographer-slam page
ArduPilot/ardupilot_wiki pull request #5366
Opened 2023-08-22 15:25 UTC by pedro-fuoco

Continuation of #5359.
The technical details have been heavily based on the  `ardupilot_ros` README, which is linked in the page

@Hwurzburg could you upload the video to Ardupilot's youtube channel ?

2023-08-31 15:26 UTC, Hwurzburg requested changes
thanks...a few nits

2023-08-31 15:26 UTC, Hwurzburg commented on dev/source/docs/ros2-cartographer-slam.rst
> +========================================
under/overlines wrong

2023-08-31 15:26 UTC, Hwurzburg commented on dev/source/docs/ros2-cartographer-slam.rst
> +------------
should use =====  for next heading level not ----

2023-08-31 15:26 UTC, Hwurzburg commented on dev/source/docs/ros2-cartographer-slam.rst
> +-----
=====

2023-08-31 15:26 UTC, Hwurzburg commented on dev/source/docs/ros2-cartographer-slam.rst
> +-------------------
========

2023-08-31 15:26 UTC, Hwurzburg commented on dev/source/docs/ros2-cartographer-slam.rst
> +----
use =====

2023-08-31 15:26 UTC, Hwurzburg commented on dev/source/docs/ros2-cartographer-slam.rst
> +..  youtube:: apZBxC2RHTM
```suggestion
..  youtube:: bpjGyAECKHA
```
new link

2023-09-02 00:08 UTC, Hwurzburg commented
thanks

2023-09-02 00:36 UTC, pedro-fuoco commented
@tridge also asked me to link the common-ekf-sources page

https://github.com/ArduPilot/ardupilot_ros/pull/12#issuecomment-1696511247

I will submit a fixup

2023-09-02 00:40 UTC, pedro-fuoco commented
@Hwurzburg Done! Let me know if I need to change anything else, thanks for the review

2023-09-02 12:08 UTC, Hwurzburg commented
Question, how would you use this on a real vehicle per the warning? via companion computer?

2023-09-03 23:57 UTC, pedro-fuoco commented
> Question, how would you use this on a real vehicle per the warning? via companion computer?

Yes, but the tutorials on how to setup ardupilot and ROS 2 with a companion computer are still not available. I suggest leaving the warning there preemptively since it is a safety measure.

2023-09-04 15:36 UTC, pedro-fuoco commented
Removed the warning about rosdep since it is now supported https://github.com/ArduPilot/ardupilot_ros/commit/ca804c8b5952a65003675e3b5b30ad116d134753

2023-09-04 22:35 UTC, Hwurzburg commented
LGTM...merging

2023-09-04 22:35 UTC, merged