Add wiki for Trimble PX-1
ArduPilot/ardupilot_wiki pull request #5540
Opened 2023-11-07 17:36 UTC by Ryanf55

The PX-1 needs a wiki entry. This should be merged together with https://github.com/ArduPilot/ardupilot/pull/25479.

One thing I think the wiki does not do a good job with, that is more of an issue of parameters, is showing which parameters are driver-specific. In order to remove any confusion for PX-1 users, I have given a list of parameters which are known to be unsupported. If there is a better way of handling this, please share.

2023-11-08 02:13 UTC, Ryanf55 commented on common/source/docs/common-positioning-landing-page.rst
> +    Trimble PX-1 RTX GNSS+INS <common-gps-trimble-px1>
I put this in the RTK header because it's similar to RTK and don't think a single GPS is deserving of its own category (yet).

2023-11-11 18:39 UTC, Ryanf55 commented on common/source/docs/common-gps-trimble-px1.rst
> +- :ref:`GPS_COM_PORT <GPS_COM_PORT>` = 1 (to use COM2, the TTL output of the PX-1) or 3 (to use COM1, the RS232 output of the PX-1)
This param is now documented directly, and the description here can be removed.

2023-12-07 14:20 UTC, Hwurzburg commented
@Ryanf55 is this ready to be changed from a draft to final PR?

2023-12-07 16:23 UTC, Ryanf55 reviewed
@Hwurzburg Yes. I've updated the entry to match the current implementation. It can be merged now.

2023-12-07 16:30 UTC, Hwurzburg commented
It wont be merged until 4.5...but will add a pointer to it in upcoming

2023-12-07 16:32 UTC, Hwurzburg requested changes

2023-12-07 16:32 UTC, Hwurzburg commented on common/source/docs/common-gps-trimble-px1.rst
> +=====================
just noticed tiltling over/underline wrong here and below

2024-01-31 23:17 UTC, merged