Common: update EKF source switching to include POSZ explanation
ArduPilot/ardupilot_wiki pull request #5855
Opened 2024-04-03 04:50 UTC by rmackay9

This makes a few changes to our EKF source switching page in response to [this support thread](https://discuss.ardupilot.org/t/arkflow-and-z-drop/115549) in which a user ended up changing the EKF_SRC1_POSZ to RangeFinder which is pretty much never a good idea.

I've also included a couple of drive-by changes:

- updated a warning on the Surface Tracking and Terrain Following pages to remove the old EKF2 info and clarify the EKF3 source set parameter involved
- added a link to Surface Tracking from the "Understanding altitudes" page
- added a link to reference frames from the "Additional Info" page to make Copter match Rover

I've tested these locally and they look OK to me.

2024-04-04 01:19 UTC, Hwurzburg requested changes

2024-04-04 23:48 UTC, rmackay9 commented on common/source/docs/common-ekf-sources.rst
> +- Option 3: GPS is recommended if the vehicle will fly long distances where the air pressure may change significantly.  In case of GPS failure the EKF will fallback to using the barometer
I had a chat with Tridge and he sais that for these long duration flights the potential for significant air pressure changes he recommends using a "high quality GPS" for height (a dual-band F9P or similar).

If it not possible to use a "high quality GPS" then use Baro and set the EK3_OGN_HGT_MSK to 5 which is 1:Correct when using Baro height" + 4:Apply corrections to local position".

So I'll update what I've written above.

2024-04-05 06:09 UTC, rmackay9 commented on common/source/docs/common-ekf-sources.rst
> +- Option 3: GPS is recommended if the vehicle will fly long distances where the air pressure may change significantly.  In case of GPS failure the EKF will fallback to using the barometer
I've updated this now.

2024-04-06 20:04 UTC, Hwurzburg commented
tnx

2024-04-06 20:04 UTC, merged