dev: correct documentation of how-to-schedule-your-code document
ArduPilot/ardupilot_wiki pull request #5952
Opened 2024-05-08 22:30 UTC by peterbarker

2024-05-08 23:55 UTC, rmackay9 commented on dev/source/docs/code-overview-scheduling-your-new-code-to-run-intermittently.rst
> +Helpers are provided to create entries in the scheduler table; see the documentation referenced above.
Thanks for this.  I think we should fill this section out a bit more though.  We should tell the user to add a new row to the scheduler task list and I actually think we should describe the helpers a little bit.  Also the "documentation referenced above" does not mention FAST_TASK.

2024-05-08 23:56 UTC, rmackay9 requested changes
A small request above to fill out one section.

2024-05-31 12:15 UTC, Hwurzburg commented
@peterbarker this needs a bit more, no?

2024-11-13 13:29 UTC, Hwurzburg commented
@peterbarker status?

2025-05-13 04:40 UTC, peterbarker commented
Sorry, no longer have my head around this one.  Maybe next time I'm in the code I'll come back to it.

2025-05-13 04:40 UTC, closed without merging