Dev: ROS: Split into ROS 1 and ROS 2 docs
ArduPilot/ardupilot_wiki pull request #5975
Opened 2024-05-12 17:12 UTC by Ryanf55

Before and After:

![image](https://github.com/ArduPilot/ardupilot_wiki/assets/25047695/a81f31ee-cf11-4bc0-88e0-416c11de486e)

I want to also recommend using ROS 2. Note the ethernet changes were because it wasn't representing in the TOC correctly. Incorrect headings were used.

2024-05-12 18:56 UTC, Hwurzburg requested changes

2024-05-12 18:56 UTC, Hwurzburg commented on dev/source/docs/ros.rst
> +=========
underline/overline error

2024-05-12 22:56 UTC, Ryanf55 commented
What do you think about moving up the `Prerequisites` section? We get a fair number of people trying to build ardupilot in a ros2 workspace before they even know what ArduPilot is or how to use ROS 2.

2024-05-13 00:15 UTC, Hwurzburg commented
I like it....first thing before ROS1/2 is even mentioned....

2024-05-13 03:28 UTC, Ryanf55 commented
> I like it....first thing before ROS1/2 is even mentioned....

Done, it's nearly at the top. I think it's work introducing ROS 1 and ROS 2, otherwise the links in the pre-reqs don't make sense.

2024-05-13 18:39 UTC, merged