Common: fix infinite recursion
ArduPilot/ardupilot_wiki pull request #6118
Opened 2024-07-16 12:35 UTC by khancyr

fix infinite recursion

2024-07-16 21:37 UTC, Hwurzburg commented
I dont understand where the recursion is without this PR that makes a lot of seemingly unrelated changes to add items to blimp

2024-07-16 22:18 UTC, khancyr commented
Recusion comes from the hidden toc on makefly rtf pages, there are two that are referencing each other. 
Removing one, then trigger a not included into doctree issue, so I move up the hidden doctree to the common rtf page. This now trigger issue with missing include for blimp, thus the massive update on blimp

2024-07-19 16:30 UTC, Hwurzburg requested changes

2024-07-19 16:30 UTC, Hwurzburg commented on common/source/docs/common-rtf.rst
> +* :ref:`MakeFLyEasy - Striver Mini Hand Throw <common-makeflyeasy-striver-mini-hand-throw>`
not a vtol, put under plane

2024-07-19 16:30 UTC, Hwurzburg commented on common/source/docs/common-rtf.rst
> +* :ref:`MakeFLyEasy - Fighter Hand Throw <common-makeflyeasy-fighter-hand-throw>`
not a vtol

2024-07-19 16:30 UTC, Hwurzburg commented on common/source/docs/common-rtf.rst
>  * `MakeFLyEasy - Freeman 2300 <https://www.aliexpress.com/item/10000223137957.html?spm=a2g0o.store_home.productList_1076398524.pic_3>`__
https://www.uavmodel.com/collections/vtol/products/makeflyeasy-freeman-4-1-2300mm-uav-vtol

not your issue but while we are doing this......

2024-07-19 16:30 UTC, Hwurzburg commented on common/source/docs/common-rtf.rst
>  * `MakeFLyEasy - Freeman 2100 <https://www.aliexpress.com/item/10000223137957.html?spm=a2g0o.store_home.productList_1076398524.pic_2>`__
https://www.uavmodel.com/products/makeflyeasy-striver-mini-4-1-4-2-2100mm-vtol-uav?variant=41656322654362

2024-08-16 05:02 UTC, Hwurzburg commented
@khancyr still awaiting changes

2024-08-29 15:04 UTC, khancyr commented
@Hwurzburg updated with corrections

2024-08-30 04:51 UTC, Hwurzburg commented on common/source/docs/common-rtf.rst
>  * `MakeFLyEasy - Freeman 2100 <https://www.aliexpress.com/item/10000223137957.html?spm=a2g0o.store_home.productList_1076398524.pic_2>`__
where is this model linked now?

2024-08-30 08:54 UTC, Hwurzburg approved these changes

2024-08-30 09:22 UTC, merged