Update VectorNav Documentation
ArduPilot/ardupilot_wiki pull request #6132
Opened 2024-07-19 23:32 UTC by lashVN

The VectorNav documentation is currently out of date, as the driver currently supports all VectorNav sensors (outside of VN-100 and VN-300).

It also should be its own page to provide more space to discuss setup.

Suggested outline:

About VectorNav

Where to buy

Hardware Setup

Firmware Configuration
1. Use sensors as inputs to ArduPilot internal filters. Configured via EAHRS_SENSORS bitmask
  - No additional necessary changes. Highly recommended to raise EAHRS_RATE to 400 or 800 Hz (which requires raising baudrate to 921600) so that AP EKF has enough data
3. Use VectorNav solution. Currently only avialable on GNSS-enabled products (not vn-100 or vn-110)
  - Additionally requires changing AHRS_EKF_TYPE to 11

Note: Configuration/connection of VN takes place at bootup, so must reboot AP after any VN configuration change (such as IMU rate or baudrate)
 
VectorNav configuration

Published Data

Links

2024-07-23 17:15 UTC, Ryanf55 commented
Hi Henry, I haven't used vectornav, I think Tridge is a better reviewer for this PR. I don't agree with this approach to duplicate the microstrain information in a vectornav-named page.

2024-08-01 16:08 UTC, lashVN commented
Hi @Hwurzburg  (or @Ryanf55 ), could you clarify what you mean that this push eliminates the other external ahrs? 

If I understand your comment correctly, you're okay with moving the VectorNav information to a standalone page. Can you clarify which information was eliminated that shouldn't be? Unless I'm misunderstanding the diff, I removed only the "VectorNav Specific Setup" section, which I'd think wouldn't be used by other external AHRS

2024-08-01 18:08 UTC, Hwurzburg commented
looks better now,,,you had removed Inertialabs and Microstrain before...will re-review this weekend...on vacation

2024-08-01 19:03 UTC, lashVN commented
@Hwurzburg 

Great, thanks so much. I'll clean up the commit history after an initial review if that's alright, I have a feeling a few things may have to change--I've never pushed to AP documentation so I may have a couple syntax/linking issues.

2024-08-01 19:28 UTC, Ryanf55 commented
This is much more in line with what I would expect. Great information. I don't have time today/this weekend to review, but can look closer next week. Cheers!

2024-08-06 04:51 UTC, Hwurzburg requested changes
many build errors:
/home/henryw/ardupilot_wiki/copter/source/docs/common-external-ahrs-vectornav.rst:75: ERROR: Unexpected indentation.
/home/henryw/ardupilot_wiki/copter/source/docs/common-external-ahrs-vectornav.rst:85: ERROR: Unexpected indentation.
/home/henryw/ardupilot_wiki/copter/source/docs/common-external-ahrs-vectornav.rst:86: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/henryw/ardupilot_wiki/copter/source/docs/common-external-ahrs-vectornav.rst:96: ERROR: Unexpected indentation.
/home/henryw/ardupilot_wiki/copter/source/docs/common-external-ahrs-vectornav.rst:97: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/henryw/ardupilot_wiki/copter/source/docs/common-external-ahrs-vectornav.rst:112: ERROR: Unexpected indentation.
/home/henryw/ardupilot_wiki/copter/source/docs/common-external-ahrs-vectornav.rst:114: WARNING: Block quote ends without a blank line; unexpected unindent.
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/henryw/ardupilot_wiki/copter/source/docs/common-external-ahrs-vectornav.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
copying assets... copying static files... done
copying extra files... done
done
writing output... [100%] index
/home/henryw/ardupilot_wiki/copter/source/docs/common-external-ahrs-vectornav.rst:52: WARNING: undefined label: 'configured binary outputs'
/home/henryw/ardupilot_wiki/copter/source/docs/common-external-ahrs-vectornav.rst:169: WARNING: undefined label: '<use as an external sensor set>'

2024-08-07 05:01 UTC, Hwurzburg commented
I can fix that...asap...on vacation...give me a few days

2024-08-07 06:38 UTC, Hwurzburg commented
fixed,squashed,rebased....will merge on CI completed

2024-08-07 13:45 UTC, merged