Update common-servo-robotis.rst
ArduPilot/ardupilot_wiki pull request #6179
Opened 2024-08-13 23:37 UTC by Jonathon-RINC

Update links to current ROBOTIS resources

2024-08-14 07:21 UTC, Hwurzburg requested changes

2024-08-14 07:21 UTC, Hwurzburg commented on common/source/docs/common-servo-robotis.rst
> +Robotis servos using the "`DYNAMIXEL Protocol 2.0 <http://emanual.robotis.com/docs/en/dxl/protocol2/>`__" are supported. The `XM430-W350-T <https://emanual.robotis.com/docs/en/dxl/x/xm430-w350/>`__ i
```suggestion
Robotis servos using the "`DYNAMIXEL Protocol 2.0 <http://emanual.robotis.com/docs/en/dxl/protocol2/>`__" are supported. The `XM430\-W350\-T <https://emanual.robotis.com/docs/en/dxl/x/xm430-w350/>`__ in particular is known to work correctly with ArduPilot.
```
Sphinx is picky about hyperlinks...this fixes the build error

2024-08-14 17:34 UTC, Jonathon-RINC commented
I accepted the change request to make Sphinx happy with the link formatting, thank you for the advisory.

2024-08-15 17:47 UTC, Hwurzburg commented
I fixed another build error and squashed...will merge on ci pass...thanks

2024-08-15 17:47 UTC, Hwurzburg approved these changes

2024-08-16 04:59 UTC, merged