Added wiki for MLX90614 I2C Sensor
ArduPilot/ardupilot_wiki pull request #6286
Opened 2024-09-18 18:54 UTC by rahulOCR

Written Wiki for PR -https://github.com/ArduPilot/ardupilot/pull/26886 submitted

2024-09-18 20:14 UTC, Hwurzburg requested changes

2024-09-18 20:14 UTC, Hwurzburg commented on common/source/docs/common-temperature-sensor.rst
> +.. note:: The MLX90614 sensor is an infrared thermometer for non-contact temperature measurements. Its I2C address is 90 so TEMP1_BUS=90 for this type of sensor.
```suggestion
.. note:: The MLX90614 sensor is an infrared thermometer for non-contact temperature measurements. Its I2C address is 90 so :ref:`TEMP1_BUS<TEMP1_BUS>` = 90 for this type of sensor.
```

2024-09-18 20:15 UTC, Hwurzburg commented
thanks for the wiki update!

2024-09-19 06:20 UTC, rahulOCR commented on common/source/docs/common-temperature-sensor.rst
> +.. note:: The MLX90614 sensor is an infrared thermometer for non-contact temperature measurements. Its I2C address is 90 so TEMP1_BUS=90 for this type of sensor.
accepted

2024-09-19 06:22 UTC, rahulOCR commented
squashing the correction commit

2024-11-13 13:11 UTC, merged