Ros2 interface
ArduPilot/ardupilot_wiki pull request #6343
Opened 2024-10-20 22:34 UTC by Ryanf55

# Purpose

Start some documentation on the ROS interface on which channels are exposed

2024-11-03 23:41 UTC, Ryanf55 commented
@pedro-fuoco  Can you review/add information to the TF , localization, and odometry sections? I'd like to make sure it has the info that your project figured out for GPS denied navigation.

2024-11-07 05:12 UTC, pedro-fuoco commented on dev/source/docs/ros2-interfaces.rst
> +The current ROS version supported is ``humble``.
Sidenote: This shouldn't stop this PR from being approved

2024-11-07 05:14 UTC, pedro-fuoco commented
I will add information to the sections you requested tomorrow

2024-11-07 22:38 UTC, Ryanf55 commented on dev/source/docs/ros2-interfaces.rst
> +The current ROS version supported is ``humble``.
Let's make sure we have CI running the existing tests for jazzy before merge.

2024-11-12 03:55 UTC, pedro-fuoco requested changes
Do the services not have a table describing their types because they are using custom ardupilot types ?

2024-11-12 03:57 UTC, pedro-fuoco requested changes
Let me know what you think about the additions I proposed. It would be best if the merge waited until `/ap/pose/filtered` is documented

2024-11-12 07:14 UTC, Ryanf55 commented
> Do the services not have a table describing their types because they are using custom ardupilot types ?

I just didn't have time to document them yet, Perhaps in a follow up they could be added.

2024-11-12 15:05 UTC, pedro-fuoco approved these changes
LGTM, we can merge once the PR dependencies are done.
Thanks for the contribution @Ryanf55!

2024-12-04 23:16 UTC, Ryanf55 commented
@Hwurzburg Please merge when you are happy. All dependencies are now merged.

2024-12-05 03:23 UTC, Hwurzburg commented
tnx

2024-12-05 03:23 UTC, merged