4.7:Add Quadplane QwikTune
ArduPilot/ardupilot_wiki pull request #6439
Opened 2024-12-10 14:07 UTC by Hwurzburg

@MichelleRos I created shell for the QwikTune PR and highlighted in bold sections that need your input...if you could squash your added commits to this to a single commit, it would save me a step later...thanks

2024-12-10 14:18 UTC, MichelleRos requested changes
This seems to be adding a new page called "qwiktune" to describe the usage of the quicktune c++ in Plane. I don't think this is the right way to go. We don't want to be maintaining two separate pages.

What I was suggesting on Discord was that we make the current quicktune page in Copter be available under Plane.

2024-12-10 14:27 UTC, Hwurzburg commented
Copter uses the LUA script not the C++ code...changing the C++ code does not impact the Copter page and vice versa...IF Copter ever adopts QwikTune then it might be worthwhile...

however, if you want to create a common page (common-quicktune.rst) the differences in text (which will be significant as will the other link changes throughout two wiki's tuning sections) can be isolated to a particular wiki with [site wiki="plane"] [/site]  or [site wiki="copter"] [/site] delimiters around wiki site specific wording, params, links, etc.

2024-12-14 14:18 UTC, Hwurzburg commented
@MichelleRos since this is back ported to 4.6, there is some urgency to complete and merge this.....can you contribute?

2024-12-16 06:34 UTC, MichelleRos commented
@Hwurzburg The intent AFAIK was to keep the Lua and C++ implementations the same (well, actually the intent was to get rid of the Lua implementation and just have the C++ implementation for both copter and plane instead of doubling our maintenance workload, but certain people refused to allow that).

As for the documentation, I don't really know whether there would be enough differences between the two to make it easier to do two separate pages, but that'd really be a question for @tridge as quicktune is really his thing.

2024-12-17 14:47 UTC, Hwurzburg commented
I have updated and will merge once Tridge approves

2024-12-17 21:49 UTC, tridge requested changes

2024-12-17 21:49 UTC, tridge commented on plane/source/docs/quicktune.rst
> +- Arm and takeoff in Loiter mode and climb to a height of about 3m
QLOITER not Loiter

2024-12-17 21:49 UTC, tridge commented on plane/source/docs/quicktune.rst
> +- If necessary reposition the vehicle using the RC transmitter.  This will temporarily pause tuning and restore the original gains.  Tuning will resume a few seconds after the RC sticks are returned
it does not restore the gains while repositioning

2024-12-17 21:49 UTC, tridge commented on plane/source/docs/quicktune.rst
> +- If the vehicle begins oscillating violently cancel the tune by moving the RC switch to the low position OR push MP's Aux Function's "Low" button
the tune will automatically abort if an angle error over QWIK_ANGLE_MAX is detected

2024-12-17 23:48 UTC, merged