Update index.html , included preload image in the head so that loadin…
ArduPilot/ardupilot_wiki pull request #6495
Opened 2024-12-29 03:22 UTC by Knowledgelocater

…g image should pe optimised

Added Preload images in the head so that loading of image should be optimised.

2025-01-03 12:49 UTC, Hwurzburg commented
@khancyr ping

2025-01-03 13:52 UTC, khancyr requested changes
Images are loaded only on need, so the only ones we should try to preload are 
slides_01_Ardupilot42.jpg, slides_01_Ardupilot42.webp, and ArduPilot-Motto.png as only those are visible on opening.

2025-01-03 16:40 UTC, khancyr commented
Need rebase and squash to have only 1 commit and it will be good !

2025-07-24 13:11 UTC, Hwurzburg commented
I squashed and merged

2025-07-24 13:11 UTC, merged